version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3330:3306
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  externalDbMySql5.7:
    image: mysql:5.7
    volumes:
      - externalDbDataMySql5.7:/var/lib/mysql
    restart: always
    ports:
      - 3331:3306
    environment:
      MYSQL_ROOT_PASSWORD: externalPassword
      MYSQL_DATABASE: externalDb
      MYSQL_USER: externalDbUser
      MYSQL_PASSWORD: externalDbPassword

  flywaySql:
    image: flyway/flyway
    command: -configFiles=/flyway/external-login/configFiles/sql.flyway migrate
    volumes:
      - ./flyway/:/flyway/external-login
    depends_on:
      - externalDbMySql5.7

  flywayWordPress:
    image: flyway/flyway
    command: -configFiles=/flyway/external-login/configFiles/wordpress.flyway migrate
    volumes:
      - ./flyway/:/flyway/external-login
    depends_on:
      - db

  wordpress:
    depends_on:
      - db
      - externalDbMySql5.7
      - flywaySql
      - flywayWordPress
    build: ./wordpress
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ./plugin-files/:/var/www/html/wp-content/plugins/external-login
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data: {}
  externalDbDataMySql5.7: {}
