version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3330:3306
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  externalDbMySql5.7:
    image: mysql:5.7
    volumes:
      - externalDbDataMySql5.7:/var/lib/mysql
    restart: always
    ports:
      - 3331:3306
    environment:
      MYSQL_ROOT_PASSWORD: externalPassword
      MYSQL_DATABASE: externalDb
      MYSQL_USER: externalDbUser
      MYSQL_PASSWORD: externalDbPassword

  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://externalDbMySql5.7/externalDb -user=externalDbUser -password=externalDbPassword -connectRetries=60 migrate
    volumes:
      - ./example-user-data/sql:/flyway/sql
    depends_on:
      - externalDbMySql5.7

  wordpress:
    depends_on:
      - db
      - externalDbMySql5.7
    build: ./wordpress
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ./plugin-files/:/var/www/html/wp-content/plugins/external-login
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data: {}
  externalDbDataMySql5.7: {}
