version: 2.0
jobs:
  build:
    machine:
      image: cimg/node:14.15.3
    steps:
      - run:
          name: Build Free
          command: node ./build-scripts/freemiusDeploy.js
  test:
    machine:
        image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: CI Setup
          command: sudo ./build-scripts/ciSetup.sh
      - run:
          name: Run Tests
          command: npm run ci-test

workflows:
  version: 2

  btd:
    jobs:
      - build
      - test
