version: 2.0
jobs:
  deployToFreemius:
    docker:
      - image: cimg/node:14.15.1
    steps:
      - checkout
      - run:
          name: Install Build Dependencies
          command: cd build-scripts && yarn
      - run:
          name: Deploy
          command: cd build-scripts && node freemiusDeploy.js
      - persist_to_workspace:
          root: ./build-scripts
          paths:
            - ./freemiusDeployVersion.json
            - ./node_modules

  fetchFreemiusBuilds:
    docker:
      - image: cimg/node:14.15.1
    steps:
      - checkout
      - attach_workspace:
          at: ./build-scripts
      - run:
          name: Fetch Freemius
          command: cd build-scripts && node freemiusFetch.js
      - persist_to_workspace:
          root: ./
          paths:
            - ./dist

  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: CI Setup
          command: sudo ./build-scripts/ciSetup.sh
      - run:
          name: Run Tests
          command: npm run ci-test

workflows:
  version: 2
  btd:
    jobs:
      - deployToFreemius
      - fetchFreemiusBuilds:
          requires:
            - deployToFreemius
      - test:
          requires:
            - fetchFreemiusBuilds
