version: 2.0
jobs:
  test:
    machine:
        image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: CI Setup
          command: sudo ./build-scripts/ciSetup.sh
      - run: npm run up
      - run: dockerize -wait http://localhost:8000 -timeout 1m
      - run: npm run test

workflows:
  version: 2

  btd:
    jobs:
      - test
